version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pr_postgres
    environment:
      POSTGRES_USER: pr_user
      POSTGRES_PASSWORD: pr_pass
      POSTGRES_DB: pr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
